[package]
name = "herold"
version = "0.1.0"
edition = "2021"
authors = ["Niklas Die√üner"]

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
phf = { version = "0.11.2", features = ["macros"] }
